// src/modules/loja/presentation/components/footer/footer.component.ts
import { CommonModule } from "@angular/common";
import { Component } from "@angular/core";

// Porta Angular de `desing system/ui_kits/site/Footer.jsx`.
@Component({
    selector: 'loja-footer',
    standalone: true,
    imports: [CommonModule],
    templateUrl: './footer.component.html',
    styleUrl: './footer.component.css',
})
export class FooterComponent { }

<footer class="loja-footer">
    <div class="loja-footer-grid">
        <div>
            <div class="loja-footer-marca">Por Onde Flor</div>
            <p class="loja-footer-descricao">Moda feminina atemporal. Cortes básicos, elegância discreta.</p>
        </div>
        <div class="loja-footer-coluna">
            <span class="loja-footer-titulo">Loja</span>
            <a href="#">Novidades</a>
            <a href="#">Roupas</a>
            <a href="#">Acessórios</a>
        </div>
        <div class="loja-footer-coluna">
            <span class="loja-footer-titulo">Ajuda</span>
            <a href="#">Trocas e devoluções</a>
            <a href="#">Guia de medidas</a>
            <a href="#">Contato</a>
        </div>
        <div class="loja-footer-newsletter">
            <span class="loja-footer-titulo">Newsletter</span>
            <input type="email" placeholder="seu e-mail" class="loja-footer-input">
        </div>
    </div>
    <div class="loja-footer-copy">© 2026 Por Onde Flor</div>
</footer>

// desing system/ui_kits/site/Footer.jsx
import React from 'react';

export function Footer() {
  return (
    <footer style={{ background: 'var(--surface-inverse)', color: 'var(--text-on-inverse)' }}>
      <div style={{ maxWidth: 'var(--container-max)', margin: '0 auto', padding: 'var(--space-8) var(--container-padding)', display: 'grid', gridTemplateColumns: '1.4fr 1fr 1fr 1fr', gap: 'var(--space-6)' }}>
        <div>
          <div style={{ font: 'var(--text-h3)', fontWeight: 300, marginBottom: 'var(--space-3)' }}>Por Onde Flor</div>
          <p style={{ font: 'var(--text-body-sm)', color: 'var(--color-neutral-300)', maxWidth: '260px' }}>Moda feminina atemporal. Cortes básicos, elegância discreta.</p>
        </div>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-3)', font: 'var(--text-body-sm)', color: 'var(--color-neutral-300)' }}>
          <span style={{ color: 'var(--text-on-inverse)', font: 'var(--text-eyebrow)', textTransform: 'uppercase', letterSpacing: 'var(--tracking-eyebrow)' }}>Loja</span>
          <a href="#" style={{ color: 'inherit', textDecoration: 'none' }}>Novidades</a>
          <a href="#" style={{ color: 'inherit', textDecoration: 'none' }}>Roupas</a>
          <a href="#" style={{ color: 'inherit', textDecoration: 'none' }}>Acessórios</a>
        </div>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-3)', font: 'var(--text-body-sm)', color: 'var(--color-neutral-300)' }}>
          <span style={{ color: 'var(--text-on-inverse)', font: 'var(--text-eyebrow)', textTransform: 'uppercase', letterSpacing: 'var(--tracking-eyebrow)' }}>Ajuda</span>
          <a href="#" style={{ color: 'inherit', textDecoration: 'none' }}>Trocas e devoluções</a>
          <a href="#" style={{ color: 'inherit', textDecoration: 'none' }}>Guia de medidas</a>
          <a href="#" style={{ color: 'inherit', textDecoration: 'none' }}>Contato</a>
        </div>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-3)' }}>
          <span style={{ font: 'var(--text-eyebrow)', textTransform: 'uppercase', letterSpacing: 'var(--tracking-eyebrow)' }}>Newsletter</span>
          <input placeholder="seu e-mail" style={{ padding: '10px 12px', border: '1px solid var(--color-neutral-600)', background: 'transparent', color: 'var(--text-on-inverse)', borderRadius: 'var(--radius-sm)', font: 'var(--text-body-sm)' }} />
        </div>
      </div>
      <div style={{ borderTop: '1px solid var(--color-neutral-800)', padding: 'var(--space-4) var(--container-padding)', font: 'var(--text-caption)', color: 'var(--color-neutral-400)', textAlign: 'center' }}>© 2026 Por Onde Flor</div>
    </footer>
  );
}
